import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import SkipNav from './components/skip-nav';
import Header from './components/header/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: ReactNode }) {
  const mainId = 'main-content';
  return (
    <html lang="en" data-theme={'emerald'}>
      <body className={inter.className}>
        <SkipNav mainId={mainId} />
        <Header />
        <main id={mainId} className="flex flex-col grow items-center">
          {children}
        </main>
      </body>
    </html>
  );
}
